<a href="https://colab.research.google.com/github/TangJiahui/6.036_Machine_Learning/blob/main/MIT_6_036_HW06_Neural_Network_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Fall 2020: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.

In [ ]:
import numpy as np

# **Problem 2**

You may find it helpful to implement a softmax function to use for solving the problems.

In [ ]:
# Implement Softmax
def SM(z):
    return np.exp(z)/np.sum(np.exp(z))

**Problem 2.A**

In [ ]:
z = np.array([[-1, 0, 1]]).T

In [ ]:
SM(z)

array([[0.09003057],
       [0.24472847],
       [0.66524096]])

**Problem 2.B**


In [ ]:
 a = np.array([[.3, .5, .2]]).T
 y = np.array([[0, 0, 1]]).T

**Problem 2.C - 2.F**

In [ ]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T

In [ ]:
a = SM(w.T@x)

In [ ]:
x@(a-y).T

array([[ 0.24472847, -0.33475904,  0.09003057],
       [ 0.24472847, -0.33475904,  0.09003057]])

In [ ]:
w_new = w -0.5*x@(a-y).T
w_new

array([[ 0.87763576, -0.83262048, -2.04501529],
       [-1.12236424,  2.16737952,  0.95498471]])

In [ ]:
SM(w_new.T@x)

array([[0.15918761],
       [0.77245284],
       [0.06835955]])

# **Problem 3**

**Problem 3.1**

You may choose to draft your implementation here. We recommend looking at the ReLU plot at the top of the homework page for better understanding.

In [ ]:
def dReLU_dz(z):
    '''
    z is a column vector
    You should return a column vector
    '''
    d = [0 if i<=0 else 1 for i in z]
    return np.array([d]).T

In [ ]:
ans=dReLU_dz(np.array([[1], [-2], [10]])).tolist()

In [ ]:
ans

[[1], [0], [1]]

In [ ]:
f2 = np.array([[15,-13]])

In [ ]:
SM(f2)

array([[1.00000000e+00, 6.91440011e-13]])